services:
  my_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_app_container
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - my_app
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    name: app_network
