version: "3.8"

services:
  my_app:
    build: .
    container_name: my_app_container
    ports:
      - "5000:5000"   # expose Flask directly on localhost for dev
    volumes:
      - .:/app        # good for local dev, can remove in prod
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"       # production entrypoint
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - my_app
    restart: always
